Wip postgres init
tsnaik/helth-bot pull request #32
Opened 2022-03-22 19:32 UTC by visajkapadia

Added dummy code with Sequelize integration.

Instructions:

1. Install Postgres on your machine.
https://www.sqlshack.com/setting-up-a-postgresql-database-on-mac/

2. Create testdb (CREATE DATABASE testdb;)
> psql posrgres
postgres> create database testdb;

4. yarn install; yarn start

Postman collection for testing db endpoints locally:
https://www.getpostman.com/collections/e5ecc05e48c460002f7c

2022-03-23 04:28 UTC, tsnaik commented
I can't comment on binary files (thanks github), so commenting here instead. do we need `.DS_Store` file?

2022-03-23 04:37 UTC, visajkapadia commented
> I can't comment on binary files (thanks github), so commenting here instead. do we need `.DS_Store` file?

Yeah that's for finder on mac. will remove it and also add it to .gitignore

2022-03-28 00:53 UTC, tsnaik requested changes
Some feedback from the initial glance. Haven't checked out and tested yet

2022-04-02 04:53 UTC, visajkapadia commented on src/server.js
> +import { dbapp } from "./routes/user.routes.js";
yup

2022-04-02 04:55 UTC, visajkapadia commented on package.json
> +    "pg": "^8.7.3",
have not added any heroku stuff. might need your help on writing README since I have not done this from scratch.

2022-04-02 04:59 UTC, visajkapadia commented on src/server.js
> -const port = process.env.PORT || 3000;
No reason. Might have added copy pasta in between. will move it back.

2022-07-31 18:46 UTC, aniketjingar approved these changes

2022-07-31 18:46 UTC, merged